Error faced:
Initally pyttsx3 module was not running it was giving the following error.
when i run the sample pyttsx3 code .

import pyttsx3

engine = pyttsx3.init()
engine.say("hello")
engine.runAndWait()

i get the following error:

Traceback (most recent call last):
File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/init.py", line 44, in init
eng = _activeEngines[driverName]
File "/usr/lib/python3.6/weakref.py", line 137, in getitem
o = self.datakey
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "speaker.py", line 3, in
engine = pyttsx3.init()
File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/init.py", line 46, in init
eng = Engine(driverName, debug)
File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/engine.py", line 52, in init
self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/driver.py", line 75, in init
self._module = importlib.import_module(name)
File "/usr/lib/python3.6/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "", line 678, in exec_module
File "", line 219, in _call_with_frames_removed
File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/drivers/espeak.py", line 5, in
from . import _espeak, toUtf8, fromUtf8
File "/home/sivaramakrishnan/.local/lib/python3.6/site-packages/pyttsx3/drivers/_espeak.py", line 18, in
dll = cdll.LoadLibrary('libespeak.so.1')
File "/usr/lib/python3.6/ctypes/init.py", line 426, in LoadLibrary
return self._dlltype(name)
File "/usr/lib/python3.6/ctypes/init.py", line 348, in init
self._handle = _dlopen(self._name, mode)
OSError: libespeak.so.1: cannot open shared object file: No such file or directory

Solution:
just run sudo apt install libespeak1
then the bug is fixed.
libspeak1 package is needed for running pyttsx3 in ubuntu.